[package]
name = "bang_web"
version = "0.1.0"
edition = "2021"

[dependencies]
local-ip-address = "0.6.2"
serde = {version = "1.0.210", features = ["derive"]}
spmc = "0.3.0"
tera = "1.20.0"
tiny_http = "0.12.0"
toml = "0.8.19"
ws = "0.9.2"
